[package]
name = "extract_netCDF"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.15"
netcdf = "0.8.1"
tokio = { version = "1.0", features = ["full"] }
